user:
  name_length: 50
  email_length: 255
  min_length: 6
  size: 50
  per_page: 10
  gio: 2
  gra_size: 30
helpers:
  size: 80
db:
  slot: 99
micropost:
  max_length: 140
  size_limit: 5
  size_gravatar: 50
shared:
  size_limit: 5
picture:
  width: 400
  height: 400
